### ISSUE TITLE
Why ALL languages uses  MIT License while C-Sharps uses (Discouraging non MIT license)?

### ISSUE THREAD

**Issue by GeorgeS2019** [TheAlgorithms/C-Sharp#277]
We need to adopt **MIT License** to be seen by the entire Github community as a true sharing spirit community.

**Comment by siriak** [comment]
What is the use case that you want to support with the MIT Licence?

**Comment by GeorgeS2019** [comment]
@siriak This is one of rare .NET projects that has potential to deliver significant impact to the .NET community. Generally, in my impression, there is less willingness for contributions among .NET developers compared to other languages e.g. python and Java. Having MIT could change this trend. More importantly, this **will prevent similar .NET algorithm GitHub repos** with MIT created elsewhere.

**Comment by maltejur** [comment]
Converting from GPL to MIT is probably pretty hard at this point since you would theoretically have to contact every contributor and ask if they are ok with the change.

**Comment by siriak** [comment]
Well, we can't contact everyone. But we can open an issue so that folks can request exclusion of their work from the repo. In any case, do we need to make a switch?

**Comment by maltejur** [comment]
I think that also comes down to the question if the algorithms in this repo should be used in real-word projects. I think most of the TheAlgorithms repos have the ambition to be "educational" and thus are not that optimized for that.

If this repo shouldn't be used in projects, I think it doesn't make sense to bother to change the license because the only thing that a change to MIT would do is make this repo usable in proprietary projects.
